// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "enable": boolean;
      "input": string;
      "apiURL": string;
      "apiKey": string;
      "model": string;
      "datalabUseLocal": boolean;
      "datalabMode": string;
      "datalabUrl": string;
      "datalabApiKey": string;
      "mistralApiKey": string;
      "datalabMaxConcurrent": number;
      "localForceOcr": boolean;
      "cloudForceOcr": boolean;
      "cloudUseLlm": boolean;
      "modelConfigs": string;
      "activeModelId": string;
    };
  }
}
